# Generated by Django 4.2.5 on 2024-01-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('rooms', '0004_alter_amenity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='catogory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
