# Generated by Django 4.2.5 on 2024-01-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_catogory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='catogory',
            new_name='category',
        ),
    ]
