# Generated by Django 4.2.5 on 2024-01-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_catogory_alter_perk_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='catogory',
            new_name='category',
        ),
    ]
